language: node_js
node_js:
  - "0.11"
  - "0.10"
branches:
  only:
    - master
install:
    - npm install
    - npm install jshint
script:
    - jshint .
    - npm test
notifications:
  email: false
